trigger trAgencyReport on AgencyReport__c (before insert, before update) { 
    if(!Test.isRunningTest()) {
        Map<String, Group_By_Waypoint__c> groupWaypointUpdateList = new Map<String, Group_By_Waypoint__c>();
        Map<String, Group_By_Agency__c> groupAgencyUpdateList = new Map<String, Group_By_Agency__c>();
        
        Set<String> groupWaypointNameSet = new Set<String>();
        Set<String> groupAgencyNameSet = new Set<String>();
        for(AgencyReport__c record : trigger.new) {
            groupWaypointNameSet.add(record.Year__c + '-' + record.Month__c + '-' + record.WaypointTaiwan__c + '-' + record.WaypointOutside__c);
            groupAgencyNameSet.add(record.Year__c + '-' + record.Month__c + '-' + record.WaypointTaiwan__c + '-' + record.WaypointOutside__c + '-' + record.Account__c);
            System.debug(record.Year__c + '-' + record.Month__c + '-' + record.WaypointTaiwan__c + '-' + record.WaypointOutside__c);
        }
        System.debug(groupWaypointNameSet);
        System.debug(groupAgencyNameSet);
        List<Group_By_Waypoint__c> groupWaypointList = [SELECT Id, Name FROM Group_By_Waypoint__c WHERE Name IN : groupWaypointNameSet AND CreatedDate = TODAY];
        System.debug(groupWaypointList);
        List<Group_By_Agency__c> groupAgencyList = [SELECT Id, Name FROM Group_By_Agency__c WHERE Name IN : groupAgencyNameSet AND CreatedDate = TODAY];
        System.debug(groupAgencyList);
        
        Map<String, Group_By_Waypoint__c> groupWaypointMap = new Map<String, Group_By_Waypoint__c>();
        
        // Populate the map with the queried records
        for (Group_By_Waypoint__c waypoint : groupWaypointList) {
            System.debug(waypoint);
            groupWaypointMap.put(waypoint.Name, waypoint);
        }
        
        Map<String, Group_By_Agency__c> groupAgencyMap = new Map<String, Group_By_Agency__c>();
        
        // Populate the map with the queried records
        for (Group_By_Agency__c agency : groupAgencyList) {
            groupAgencyMap.put(agency.Name, agency);
        }
        
        for(AgencyReport__c record : trigger.new) {
            String tempGWName = record.Year__c + '-' + record.Month__c + '-' + record.WaypointTaiwan__c + '-' + record.WaypointOutside__c;
            Group_By_Waypoint__c tempGroupWaypoint = groupWaypointMap.get(tempGWName);
            System.debug(tempGWName);
            System.debug(tempGroupWaypoint);
            record.Group_By_Waypoint__c = tempGroupWaypoint.Id;
            if(!groupWaypointUpdateList.keySet().contains(tempGWName)) {
                tempGroupWaypoint.WaypointTaiwan__c = record.WaypointTaiwan__c;
                tempGroupWaypoint.WaypointOutside__c = record.WaypointOutside__c;
                tempGroupWaypoint.Area__c = record.Area__c;
                tempGroupWaypoint.Year__c = record.Year__c;
                tempGroupWaypoint.Month__c = record.Month__c;
                tempGroupWaypoint.Departing_Flight_Date__c = record.Departing_Flight_Date__c;
                groupWaypointUpdateList.put(tempGWName, tempGroupWaypoint);
            }
            
            String tempGAName = record.Year__c + '-' + record.Month__c + '-' + record.WaypointTaiwan__c + '-' + record.WaypointOutside__c + '-' + record.Account__c;
            //System.debug(tempGAName);
            Group_By_Agency__c tempGroupAgency = groupAgencyMap.get(tempGAName);
            record.Group_By_Agency__c = tempGroupAgency.Id;
            if(!groupWaypointUpdateList.keySet().contains(tempGAName)) {
                tempGroupAgency.WaypointTaiwan__c = record.WaypointTaiwan__c;
                tempGroupAgency.WaypointOutside__c = record.WaypointOutside__c;
                tempGroupAgency.Agency__c = record.Account__c;
                tempGroupAgency.Area__c = record.Area__c;
                tempGroupAgency.Year__c = record.Year__c;
                tempGroupAgency.Month__c = record.Month__c;
                tempGroupAgency.Departing_Flight_Date__c = record.Departing_Flight_Date__c;
                groupAgencyUpdateList.put(tempGAName, tempGroupAgency);
            }
        }
        
        if (!groupWaypointUpdateList.isEmpty()) update groupWaypointUpdateList.values();
        
        if (!groupAgencyUpdateList.isEmpty()) update groupAgencyUpdateList.values();
        System.debug(groupWaypointUpdateList);
        System.debug(groupAgencyUpdateList);
    } else {
        Integer a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
            a = 0;
    }
}