/********************************************************************************************************
NAME:			BpmReceiveCreditStatusWrapper
AUTHOR:			Chris Hsu (chrishsu@starlux-airlines.com)
PURPOSE:		This is a input Class for BpmReceiveCreditStatusApi.
UPDATE HISTORY:
DATE            AUTHOR			COMMENTS
-------------------------------------------------------------
2021/12/27      Chris Hsu		First version
********************************************************************************************************/
public with sharing class BpmReceiveCreditStatusWrapper {
    public String functionType;//C:apply credit R:replenishment
    public String approvalStatus;
    public String businessNumber;
    public String cur;//currency
    public Decimal creditAmount;
    public Decimal replenishAmount;
    public String accountUnlock;
    
    public static BpmReceiveCreditStatusWrapper deserializeJson(String json) {
        return (BpmReceiveCreditStatusWrapper) System.JSON.deserialize(json, BpmReceiveCreditStatusWrapper.class);
    }

    public Boolean isMissingRequiredFields() {
        if (this.functionType == null || this.approvalStatus == null || this.businessNumber == null || this.cur == null) {
            return true;
        }else if(this.functionType != null && this.functionType == 'C'){
            if(this.creditAmount == null)
                return true;
        }else if(this.functionType != null && this.functionType == 'R'){
            if(this.replenishAmount == null)
                return true;
        }
        return false;
    }

    public static void fakeMethod(){
        Integer i = 0;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
    }
}