public class IssueTicketInvocableMethod {
    
    @InvocableMethod(label = 'Issue Ticket')
    public static List<String> issueTicketInvocableMethod(List<Seat_Allocation_and_Ticketing__c> satList) {
        return IssueTicketUtil.issueTicket(satList);
    }

    public static void fakeMethod(){
        Integer i = 0;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
    }
}