public without sharing class UrlConstants {
    public final static String LOGIN = 'Login';
    public final static String FORGOT_PASSWORD = 'B2BForgotPassword';
    public final static String HOME = 'Home';
    public final static String RESET_PASSWORD = 'ResetPassword';
    public final static String EditTraveler = 'EditTraveler';
    public final static String AccountManagement = 'AccountManagement';
    public final static String AccountMaintain = 'AccountMaintain';
    public final static String HistoryLog = 'HistoryLog';
}